boards/api/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import (
    BoardListCreateAPIView,
    BoardRetrieveUpdateDestroyAPIView,
    GetSubscribedBoards,
    SubscribeBoardView,
    TrendingBoardsList,
)

urlpatterns = [
    url(r'^boards/$', BoardListCreateAPIView.as_view(), name='list_or_create_boards'),
    url(r'^boards/(?P<slug>[-\w]+)/$',
        BoardRetrieveUpdateDestroyAPIView.as_view(),
        name='retrieve_or_update_or_destroy_boards'),
    url(r'^actions/subscribe/$', SubscribeBoardView.as_view()),
    url(r'^top_five_boards/$', TrendingBoardsList.as_view()),
    url(r'^user_subscribed_boards/$', GetSubscribedBoards.as_view()),
]

mysite/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token,verify_jwt_token


import boards.views as boards_views
import comments.views as comments_views
import notifications.views as notifications_views
import reports.views as reports_views
import search.views as search_views
import subjects.views as subjects_views
import users.views as users_views
from subjects.sitemaps import SubjectSitemap

sitemaps = {
    'subjects': SubjectSitemap,
}

urlpatterns = [
    re_path(r'^$', subjects_views.HomePageView.as_view(), name='home'),
    re_path(r'^trending/$', subjects_views.TrendingPageView.as_view(), name='trending'),
    re_path(r'^s/(?P<board>[-\w]+)/(?P<subject>[-\w]+)/$', subjects_views.subject_detail, name='subject_detail'),
    re_path(r'^b/$', boards_views.BoardsPageView.as_view(), name='view_all_boards'),
    re_path(r'^b/(?P<board>[-\w]+)/$', boards_views.BoardPageView.as_view(), name='board'),
    re_path(r'^b/ban_user/(?P<board>[-\w]+)/(?P<user_id>\d+)/$', boards_views.ban_user, name='ban_user'),
    re_path(r'^b/(?P<board>[-\w]+)/edit_board_cover/$', boards_views.edit_board_cover, name='edit_board_cover'),
    re_path(r'^b/(?P<board>[-\w]+)/subscription/$', boards_views.subscribe, name='subscribe'),
    re_path(r'^b/(?P<subject>[-\w]+)/like/$', subjects_views.like_subject, name='like'),
    re_path(r'^load_new_comments/$', comments_views.load_new_comments, name='load_new_comments'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/subscriptions/$',
            boards_views.UserSubscriptionListView.as_view(),
            name='user_subscription_list'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/boards/$',
            boards_views.UserCreatedBoardsPageView.as_view(),
            name='user_created_boards'),
    re_path(r'^new_post/$', subjects_views.new_subject, name='new_subject'),
    re_path(r'^delete_post/(?P<subject>[-\w]+)/$', subjects_views.delete_subject, name='delete_subject'),
    re_path(r'^edit_subject/(?P<subject>[-\w]+)/$', subjects_views.edit_subject, name='edit_subject'),
    re_path(r'^delete_comment/(?P<pk>\d+)/$', comments_views.delete_comment, name='delete_comment'),
    re_path(r'^new_board/$', boards_views.new_board, name='new_board'),

    # user profiles
    re_path(r'^u/$', users_views.UsersPageView.as_view(), name='view_all_users'),
    re_path(r'^u/following/$', users_views.FollowingPageView.as_view(), name='view_following'),
    re_path(r'^u/followers/$', users_views.FollowersPageView.as_view(), name='view_all_followers'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/$', users_views.UserProfilePageView.as_view(), name='user_profile'),
    re_path(r'^u/follow_user/(?P<user_id>\d+)/$', users_views.follow_user, name='follow_user'),
    re_path(r'^u/send_message_request/(?P<user_id>\d+)/$',
            users_views.send_message_request,
            name='send_message_request'),
    re_path(r'^u/accept_message_request/(?P<user_id>\d+)/$',
            users_views.accept_message_request,
            name='accept_message_request'),
    re_path(r'^u/block_spammer/(?P<user_id>\d+)/$', users_views.block_spammer, name='block_spammer'),
    re_path(r'^u/friends/all/$', users_views.all_friends, name='all_friends'),
    re_path(r'^u/friends/requests/$', users_views.all_message_requests, name='all_message_requests'),
    re_path(r'^activities/$', notifications_views.ActivitiesPageView.as_view(), name='activities'),
    re_path(r'^activities/check/$', notifications_views.check_activities, name='check_activities'),

    # login / logout urls
    re_path(r'^login/$', auth_views.LoginView.as_view(extra_context={'form_filling': True}), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    re_path(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # password change re_paths
    re_path(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    re_path(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # password reset
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(),
            name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # user registration
    re_path(r'^signup/$', users_views.register_user, name='signup'),

    # verify username availability in database via ajax request
    re_path(r'^signup/check_username/$', users_views.check_username, name='check_username'),

    # profile edit
    re_path(r'^profile_edit/$', users_views.profile_edit, name='profile_edit'),
    re_path(r'^picture_change/$', users_views.change_picture, name='picture_change'),

    # search
    re_path(r'^search/$', search_views.search, name='search'),
    re_path(r'^board_search/(?P<board_slug>[-\w]+)/$', search_views.search, name='board_search'),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),

    # report
    re_path(r'^banned_users/(?P<board>[-\w]+)/$', boards_views.banned_users, name='banned_users'),
    re_path(r'^report_subject/(?P<subject>[-\w]+)/$', reports_views.report_subject, name='report_subject'),
    re_path(r'^report_comment/(?P<pk>\d+)/$', reports_views.report_comment, name='report_comment'),
    re_path(r'^show_reports/(?P<board>[-\w]+)/$', reports_views.show_reports, name='show_reports'),
    re_path(r'^deactivate_subject/(?P<subject>[-\w]+)/$', subjects_views.deactivate_subject,
            name='deactivate_subject'),
    re_path(r'^deactivate_comment/(?P<pk>\d+)/$', comments_views.deactivate_comment, name='deactivate_comment'),
    re_path(r'^messages/', include('messenger.urls')),

    # api urls
    re_path(r'^api/auth/token/obtain/', obtain_jwt_token),
    re_path(r'^api/auth/token/refresh/', refresh_jwt_token),
    re_path(r'^api/auth/token/verify/', verify_jwt_token),
    re_path(r'^api/frontboard/', include('subjects.api.urls')),
    re_path(r'^api/frontboard/', include('boards.api.urls')),
    re_path(r'^api/frontboard/', include('reports.api.urls')),
    re_path(r'^api/frontboard/', include('comments.api.urls')),
    re_path(r'^api/users/', include('users.api.urls')),
    re_path(r'^api/users/', include('notifications.api.urls')),
    re_path(r'^api/messages/', include('messenger.api.urls')),
]

if True:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# flatpages urls
urlpatterns.append(re_path(r'^', include('django.contrib.flatpages.urls')))

boards/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import m2m_changed
from django.urls import reverse
from django.utils import timezone

from slugify import UniqueSlugify


class Board(models.Model):
    """
    Model that represents a board.
    """
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=500)
    cover = models.ImageField(upload_to='board_covers/', blank=True, null=True)
    admins = models.ManyToManyField(User, related_name='inspected_boards')
    subscribers = models.ManyToManyField(User, related_name='subscribed_boards')
    banned_users = models.ManyToManyField(User, related_name='forbidden_boards')
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        """Unicode representation for a board model."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = board_slugify(f"{self.title}")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Return absolute url for a board."""
        return reverse('board', args=[self.slug])

    def get_admins(self):
        """Return admins of a board."""
        return self.admins.all()

    def get_picture(self):
        """Return cover url (if any) of a board."""
        default_picture = settings.STATIC_URL + 'img/cover.png'
        if self.cover:
            return self.cover.url
        else:
            return default_picture

    def recent_posts(self):
        """
        Counts number of posts posted within last 3 days in a board.
        """
        return self.submitted_subjects.filter(created__gte=timezone.now() - timedelta(days=3)).count()


def admins_changed(sender, **kwargs):
    """
    Signals the Board to not assign more than 3 admins to a board.
    """
    if kwargs['instance'].admins.count() > 3:
        raise ValidationError("You can't assign more than three admins.")


m2m_changed.connect(admins_changed, sender=Board.admins.through)  # noqa: E305


def board_unique_check(text, uids):
    if text in uids:
        return False
    return not Board.objects.filter(slug=text).exists()


board_slugify = UniqueSlugify(unique_check=board_unique_check,
                              to_lower=True,
                              max_length=80,
                              separator='_',
                              capitalize=False)

boards/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django import forms

from .models import Board


class BoardForm(forms.ModelForm):
    """
    Form that handles board data.
    """
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))
    cover = forms.ImageField(widget=forms.FileInput(),
                             help_text="Image dimensions should be <b>900 &#10005; 300</b>.",
                             required=False)

    class Meta:
        model = Board
        fields = ('title', 'description', 'cover')

boards/api/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView

from boards.models import Board

from .pagination import BoardPageNumberPagination
from .permissions import IsAdminOrReadOnly
from .serializers import BoardSerializer


class BoardListCreateAPIView(ListCreateAPIView):
    """
    View that returns a list of boards & handles the creation of
    boards & returns data back.
    """
    queryset = Board.objects.all()
    serializer_class = BoardSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]
    pagination_class = BoardPageNumberPagination
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title']


class BoardRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    """
    View that retrieve, update or delete (if user is the admin of) the board.
    """
    queryset = Board.objects.all()
    serializer_class = BoardSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAdminOrReadOnly]
    lookup_field = 'slug'
    lookup_url_kwarg = 'slug'


class SubscribeBoardView(APIView):
    def get(self, request, format=None):
        """
        View that subscribe / unsubscribe a board and returns action status.
        """
        data = dict()
        user = request.user
        board_slug = request.GET.get('board_slug')
        board = Board.objects.get(slug=board_slug)
        user = request.user
        if board in user.subscribed_boards.all():
            board.subscribers.remove(user)
            data['is_subscribed'] = False
        else:
            board.subscribers.add(user)
            data['is_subscribed'] = True

        data['total_subscribers'] = board.subscribers.count()
        return Response(data)


class GetSubscribedBoards(APIView):
    def get(self, request, format=None):
        """Return a list of user subscribed boards."""
        boards = request.user.subscribed_boards.all()
        boards_list = [{'id': board.id, 'title': board.title} for board in boards]
        return Response(boards_list)


class TrendingBoardsList(APIView):
    def get(self, request, format=None):
        """Return a list of trending boards."""
        boards = Board.objects.all()
        trending_boards = sorted(boards, key=lambda instance: instance.recent_posts(), reverse=True)[:5]
        trending_boards_list = [{'title': board.title, 'slug': board.slug} for board in trending_boards]
        return Response(trending_boards_list)

boards/templates/boards/banned_users.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Utilisateurs bannis | SNIS</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Banned Users" %}
{% if users %}
<p class="text-muted text-center">Annulez ban s'il a été effectuez par erreur.</p>
{% endif %}

{% for user in users %}
<div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
  <div class="card-body p-4">

    <div class="text-center" style="float:left; width:10%;">
      {% if user.profile.get_picture %}
      <img src="{{user.profile.get_picture}}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h6>
        <a href="{% url 'user_profile' user.username %}"
           class="card-link">{{ user.profile.screen_name }}</a> &nbsp; &nbsp; &nbsp;
        <a href="{% url 'ban_user' board.slug user.id %}"
           class="btn btn-outline-secondary btn-sm">Annuler ban</a>
      </h6>
    </div>
  </div>
</div>
{% empty %}
<p class="text-muted text-center">Pas d'utilisateur banni encore !</p>
{% endfor %}

{% endblock content %}

boards/templates/boards/board.html
{% extends "base.html" %}

{% block title %}<title>{{ board.title }} | Elmer</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text=board.title|upper %}
{% if subjects %}
  {% include "includes/partial_subject.html" with subjects=subjects %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">Pas de sujets trouvé.</b></h6>
    <div style="margin:0 auto;">
    <p class="text-muted">SOyez le premier à poster dans cette catégorie.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

boards/templates/boards/edit_board_cover.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Change Your Board Cover | Elmer</title>{% endblock %}


{% block form_content %}

{% include "includes/page_heading.html" with text="Change Your Board Cover" %}
{% if board_form.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{board_form.errors}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_cover">Photo de couverture.</label>
    <input type="file" class="form-control-file" id="id_cover" name="cover" accept="image/*">
  </div>
   <button type="submit" class="btn btn-primary btn-block" id="submit_cover">Submit</button>
</form>


<script type="text/javascript">
// Check file size
$(document).ready(function(){
  $("input#id_cover").on("change", function () {
    var file_size = this.files[0].size;
    if (file_size > 2097152) {
      alert("Image size should be less than 2 megabytes.")
      $("button#submit_cover").prop('disabled', true);
    } else {
        $("button#submit_cover").prop('disabled', false);
    }
  });
});
</script>

{% endblock %}

boards/templates/boards/new_board.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}<title>Create Board | Elmer</title>{% endblock %}

{% block form_content %}
{% include "includes/page_heading.html" with text="Create Board" %}

<form action="{% url 'new_board' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ board_form|crispy }}
 <button type="submit" class="btn btn-success btn-block">Envoyer</button>
</form>
{% endblock %}

boards/templates/boards/user_created_boards.html
{% extends "base.html" %}

{% block title %}<title>Your boards | Elmer</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Your Boards" %}
{% if user_boards %}
  {% include "includes/partial_board.html" with boards=user_boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">Pas de catégorie trouvé.</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">VOus n'avez pas encore créer de catégorie.</p>
    </div>
  </div>
{% endif %}

<script type="text/javascript">
// Subscribe boards
$(document).ready(function(){
  $("a#subscribe_board").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $msg=$(this);
    var $subscribe_url=$(this).attr("href");
    var $board_subscribers=$('span#board_subscribers')
    $.ajax({
      url: $subscribe_url,
      type: 'GET',
      success: function (data) {
        if ($msg.text() == 'Subscribe') {
          $msg.removeClass('btn-primary');
          $msg.addClass('btn-secondary');
          $msg.text('Unsubscribe');
          $board_subscribers.text(data + ' readers');
        } else if ($msg.text() == 'Unsubscribe') {
          $msg.removeClass('btn-secondary');
          $msg.addClass('btn-primary');
          $msg.text('Subscribe');
          $board_subscribers.text(data + ' readers');
        } else { console.log('Unexpected error!'); }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

{% endblock %}

boards/templates/boards/user_subscription_list.html
{% extends "base.html" %}

{% block title %}<title>Liste d'abonnements | SNIS</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscription List" %}
<div class="alert alert-light text-center" role="alert">
  Souscrivez aux catégories qui vous intéressent pour avoir leur actualité.
</div>
{% if subscriptions %}
  {% include "includes/partial_board.html" with boards=subscriptions %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">Pas d'abonnements trouvé.</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">VOus n'avez souscrit à aucune catégorie.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

boards/templates/boards/view_all_boards.html
{% extends "base.html" %}

{% block title %}<title>Catégorie abonnés | subscriptions</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscribe Boards" %}
<div class="alert alert-light text-center" role="alert">
  Cliquer sur <span class="font-weight-bold">S'abonner'</span> pour recevoir les actualités.
</div>
{% if boards %}
  {% include "includes/partial_board.html" with boards=boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">PAs de catégorie trouvé.</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">Il n'y a pas de catégorie créer encore.</p>
    </div>
  </div>
{% endif %}

{% endblock %}