mysite/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token,verify_jwt_token


import boards.views as boards_views
import comments.views as comments_views
import notifications.views as notifications_views
import reports.views as reports_views
import search.views as search_views
import subjects.views as subjects_views
import users.views as users_views
from subjects.sitemaps import SubjectSitemap

sitemaps = {
    'subjects': SubjectSitemap,
}

urlpatterns = [
    re_path(r'^$', subjects_views.HomePageView.as_view(), name='home'),
    re_path(r'^trending/$', subjects_views.TrendingPageView.as_view(), name='trending'),
    re_path(r'^s/(?P<board>[-\w]+)/(?P<subject>[-\w]+)/$', subjects_views.subject_detail, name='subject_detail'),
    re_path(r'^b/$', boards_views.BoardsPageView.as_view(), name='view_all_boards'),
    re_path(r'^b/(?P<board>[-\w]+)/$', boards_views.BoardPageView.as_view(), name='board'),
    re_path(r'^b/ban_user/(?P<board>[-\w]+)/(?P<user_id>\d+)/$', boards_views.ban_user, name='ban_user'),
    re_path(r'^b/(?P<board>[-\w]+)/edit_board_cover/$', boards_views.edit_board_cover, name='edit_board_cover'),
    re_path(r'^b/(?P<board>[-\w]+)/subscription/$', boards_views.subscribe, name='subscribe'),
    re_path(r'^b/(?P<subject>[-\w]+)/like/$', subjects_views.like_subject, name='like'),
    re_path(r'^load_new_comments/$', comments_views.load_new_comments, name='load_new_comments'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/subscriptions/$',
            boards_views.UserSubscriptionListView.as_view(),
            name='user_subscription_list'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/boards/$',
            boards_views.UserCreatedBoardsPageView.as_view(),
            name='user_created_boards'),
    re_path(r'^new_post/$', subjects_views.new_subject, name='new_subject'),
    re_path(r'^delete_post/(?P<subject>[-\w]+)/$', subjects_views.delete_subject, name='delete_subject'),
    re_path(r'^edit_subject/(?P<subject>[-\w]+)/$', subjects_views.edit_subject, name='edit_subject'),
    re_path(r'^delete_comment/(?P<pk>\d+)/$', comments_views.delete_comment, name='delete_comment'),
    re_path(r'^new_board/$', boards_views.new_board, name='new_board'),

    # user profiles
    re_path(r'^u/$', users_views.UsersPageView.as_view(), name='view_all_users'),
    re_path(r'^u/following/$', users_views.FollowingPageView.as_view(), name='view_following'),
    re_path(r'^u/followers/$', users_views.FollowersPageView.as_view(), name='view_all_followers'),
    re_path(r'^u/(?P<username>[\w.@+-]+)/$', users_views.UserProfilePageView.as_view(), name='user_profile'),
    re_path(r'^u/follow_user/(?P<user_id>\d+)/$', users_views.follow_user, name='follow_user'),
    re_path(r'^u/send_message_request/(?P<user_id>\d+)/$',
            users_views.send_message_request,
            name='send_message_request'),
    re_path(r'^u/accept_message_request/(?P<user_id>\d+)/$',
            users_views.accept_message_request,
            name='accept_message_request'),
    re_path(r'^u/block_spammer/(?P<user_id>\d+)/$', users_views.block_spammer, name='block_spammer'),
    re_path(r'^u/friends/all/$', users_views.all_friends, name='all_friends'),
    re_path(r'^u/friends/requests/$', users_views.all_message_requests, name='all_message_requests'),
    re_path(r'^activities/$', notifications_views.ActivitiesPageView.as_view(), name='activities'),
    re_path(r'^activities/check/$', notifications_views.check_activities, name='check_activities'),

    # login / logout urls
    re_path(r'^login/$', auth_views.LoginView.as_view(extra_context={'form_filling': True}), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    re_path(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # password change re_paths
    re_path(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    re_path(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # password reset
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(),
            name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # user registration
    re_path(r'^signup/$', users_views.register_user, name='signup'),

    # verify username availability in database via ajax request
    re_path(r'^signup/check_username/$', users_views.check_username, name='check_username'),

    # profile edit
    re_path(r'^profile_edit/$', users_views.profile_edit, name='profile_edit'),
    re_path(r'^picture_change/$', users_views.change_picture, name='picture_change'),

    # search
    re_path(r'^search/$', search_views.search, name='search'),
    re_path(r'^board_search/(?P<board_slug>[-\w]+)/$', search_views.search, name='board_search'),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),

    # report
    re_path(r'^banned_users/(?P<board>[-\w]+)/$', boards_views.banned_users, name='banned_users'),
    re_path(r'^report_subject/(?P<subject>[-\w]+)/$', reports_views.report_subject, name='report_subject'),
    re_path(r'^report_comment/(?P<pk>\d+)/$', reports_views.report_comment, name='report_comment'),
    re_path(r'^show_reports/(?P<board>[-\w]+)/$', reports_views.show_reports, name='show_reports'),
    re_path(r'^deactivate_subject/(?P<subject>[-\w]+)/$', subjects_views.deactivate_subject,
            name='deactivate_subject'),
    re_path(r'^deactivate_comment/(?P<pk>\d+)/$', comments_views.deactivate_comment, name='deactivate_comment'),
    re_path(r'^messages/', include('messenger.urls')),

    # api urls
    re_path(r'^api/auth/token/obtain/', obtain_jwt_token),
    re_path(r'^api/auth/token/refresh/', refresh_jwt_token),
    re_path(r'^api/auth/token/verify/', verify_jwt_token),
    re_path(r'^api/frontboard/', include('subjects.api.urls')),
    re_path(r'^api/frontboard/', include('boards.api.urls')),
    re_path(r'^api/frontboard/', include('reports.api.urls')),
    re_path(r'^api/frontboard/', include('comments.api.urls')),
    re_path(r'^api/users/', include('users.api.urls')),
    re_path(r'^api/users/', include('notifications.api.urls')),
    re_path(r'^api/messages/', include('messenger.api.urls')),
]

if True:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# flatpages urls
urlpatterns.append(re_path(r'^', include('django.contrib.flatpages.urls')))

users/api/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import (
    ProfileRetrieveAPIView,
    UserLoginAPIView,
    UserSignUpAPIView,
    current_user,
)

urlpatterns = [
    url(r'^login/', UserLoginAPIView.as_view(), name='users_login'),
    url(r'^signup/', UserSignUpAPIView.as_view(), name='users_signup'),
    url(r'^current_user/', current_user, name='current_user'),
    url(r'^profile/(?P<username>[-\w]+)/', ProfileRetrieveAPIView.as_view(), name='profile_info'),
]

users/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Profile(models.Model):
    """
    Model that represents a profile.
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
    dp = models.ImageField(upload_to='dps/', blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    followers = models.ManyToManyField(User, related_name='following', blank=True)
    contact_list = models.ManyToManyField(User, related_name='contacters', blank=True)
    pending_list = models.ManyToManyField(User, related_name='my_pending_requests', blank=True)
    member_since = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-member_since', )

    def __str__(self):
        """Unicode representation for a profile model."""
        return self.user.username

    def screen_name(self):
        """Returns screen name."""
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:  # noqa: E722
            return self.user.username

    def get_picture(self):
        """Returns profile picture url (if any)."""
        default_picture = settings.STATIC_URL + 'img/ditto.jpg'
        if self.dp:
            return self.dp.url
        else:
            return default_picture


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    """
    Signals the Profile about User creation.
    """
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class SignupForm(forms.ModelForm):
    """
    Form that handles signup data.
    """
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserEditForm(forms.ModelForm):
    """
    Form that handles user data.
    """
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    """
    Form that handles profile data.
    """
    class Meta:
        model = Profile
        fields = ('dob', 'dp')

users/api/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user_model

from rest_framework.decorators import api_view
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import (
    HTTP_200_OK,
    HTTP_201_CREATED,
    HTTP_400_BAD_REQUEST,
)
from rest_framework.views import APIView

from .serializers import (
    CurrentUserDetailSerializer,
    ProfileRetrieveSerializer,
    UserLoginSerializer,
    UserSerializerWithToken,
)

User = get_user_model()


@api_view(['GET'])
def current_user(request):
    """
    Determine the current user by their token, and return their data
    """
    serializer = CurrentUserDetailSerializer(request.user, context={"request": request})
    return Response(serializer.data)


class UserSignUpAPIView(APIView):
    """
    View that handles user signup and returns username, email & JWT.
    """
    permission_classes = [AllowAny]

    def post(self, request, format=None):
        serializer = UserSerializerWithToken(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=HTTP_201_CREATED)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class UserLoginAPIView(APIView):
    """
    View that handles user login and returns username & JWT.
    """
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class ProfileRetrieveAPIView(RetrieveAPIView):
    """
    View that returns user profile data.
    """
    queryset = User.objects.all()
    serializer_class = ProfileRetrieveSerializer
    lookup_field = 'username'
    lookup_url_kwarg = 'username'

users/templates/users/change_picture.html
{% extends "base.html" %}
{% block title %}<title>Account Settings | Elmer</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Account Settings" %}

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profile_edit' %}">Edit profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'picture_change' %}">Add picture</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
  </li>
</ul>

<div class="container" style="text-align:center;">
  <img src="{{request.user.profile.get_picture}}" width="300px" height="300px">
</div>

<form action="{% url 'picture_change' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_dp">Upload a picture</label>
    <input type="file" class="form-control-file" id="id_dp" name="dp" accept="image/*">
  </div>
 <button type="submit" class="btn btn-primary btn-block" id="submit_pic">Submit</button>
</form>
{% endblock %}

users/templates/users/followers.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Followers | Elmer</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Followers" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Followers Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any followers right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/following.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Following | Elmer</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Following" %}
{% for profile in profiles %}
<div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
  <div class="card-body p-4">

    <div class="text-center" style="float:left; width:10%;">
      {% if profile.user.profile.get_picture %}
      <img src="{{ profile.user.profile.get_picture }}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h5 style="font-size:16px;">
        <a href="{% url 'user_profile' profile.user.username %}"
           class="card-link"
           title="{{ profile.user.username }}">{{ profile.screen_name }}</a>
         </h5>
      <p class="text-muted">Member since <span title="{{ profile.member_since|date:"D d M Y" }} | {{ profile.member_since|time:"H:i:s" }}">{{ profile.member_since|naturaltime }}</span></p>
    </div>
  </div>
</div>
{% empty %}
<div class="card p-4 my-4 mx-0">
  <h6 class="text-center">No Following Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any following right now.</p>
  </div>
</div>
{% endfor %}

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}<title>{{user.profile.screen_name}} | Elmer</title>{% endblock %}

{% block content %}

{% if request.user.username == user.username %}
  {% include "includes/page_heading.html" with text="Your Profile" %}
{% else %}
  {% include "includes/page_heading.html" with text=user.profile.screen_name %}
{% endif %}

<style>
#profile_user_links a { border-radius: 100px; padding: 4px 15px; margin:15px; border: 1px solid #d6d6d6; }
#profile_user_links a:hover { border: 1px solid #3f51b5; }
</style>

<div class="card" style="width:25%; float:left; border:none;">
  <img class="card-img-top" src="{{ user.profile.get_picture }}">
</div>

<div class="card" style="width:75%; float:right; border:none;">
  <div class="card-body">
    <h4 class="card-title">
    {{ user.profile.screen_name }} &nbsp;
    {% ifequal request.user user %}
    {% else %}
      {% if not request.user in user.profile.contact_list.all %}
        {% if request.user in user.profile.pending_list.all %}
            <a href="{% url 'send_message_request' user.id %}"
               class="btn btn-primary btn-sm"
               id="send_message_request"
               style="margin-right: 10px;"
               title="Request sent to this users">Request Sent</a>
        {% else %}
            <a href="{% url 'send_message_request' user.id %}"
               class="btn btn-outline-primary btn-sm"
               id="send_message_request"
               style="margin-right: 10px;"
               title="Send request to this user to start conversation">Send Request</a>
        {% endif %}
      {% else %}
            <!-- Block User Trigger -->
            <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#blockUserModel">Block</button>

            <!-- Block User Modal -->
            <div class="modal fade" id="blockUserModel" tabindex="-1" role="dialog" aria-labelledby="Block User" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <h5>Once you block the user, you can not message him again until he accepts your request.</h5><br>
                    <p>If user is being annoying to you, block him right away.</p>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                    <a href="{% url 'block_spammer' user.id %}" class="btn btn-primary btn-sm" id="block_spammer" style="margin-right: 10px;" title="Block this user">Block</a>
                  </div>
                </div>
              </div>
            </div>
            <a href="{% url 'messages' user.username %}" class="btn btn-outline-primary btn-sm" id="send_msg" title="Send message to this user" style="margin-right: 10px;">Message</a>
      {% endif %}
    {% endifequal %}

    {% ifequal request.user user %}
    {% else %}
    	{% if request.user in user.profile.followers.all %}
      		<a href="{% url 'follow_user' user.id %}" class="btn btn-primary btn-sm" id="follow_user">Unfollow</a>
    	{% else %}
        	<a href="{% url 'follow_user' user.id %}" class="btn btn-outline-primary btn-sm" id="follow_user">Follow</a>
    	{% endif %}
    {% endifequal %}

    </h4>
    <p class="card-text"><strong>{{user.inspected_boards.count}}</strong> boards created.</p>
    <p class="card-text"><strong>{{user.posted_subjects.count}}</strong> subjects posted.</p>
    <p class="card-text"><strong>{{user.subscribed_boards.count}}</strong> boards subscribed.</p>
    <p class="card-text">Member since <span title="{{ user.profile.member_since|date:"D d M Y" }} | {{ user.profile.member_since|time:"H:i:s" }}">{{ user.profile.member_since|date:"M d Y" }}</span></p>
    <br>
    <p id="profile_user_links" style="text-align:center;"><a href="{% url 'user_subscription_list' user.username %}" class="card-link">View subscription list</a><span> &middot; </span>
    {% ifequal request.user user %}
    <a href="{% url 'profile_edit' %}" class="card-link">Edit profile</a><br><br>
    <a href="{% url 'view_all_followers' %}" class="card-link">Followers</a><span> &middot; </span>
    <a href="{% url 'view_following' %}" class="card-link">Following</a><br><br>
    <a href="{% url 'all_message_requests' %}" class="card-link">Message requests</a><span> &middot; </span>
    <a href="{% url 'all_friends' %}" class="card-link">Contact list</a></p>
    {% endifequal %}
  </div>
</div>

<div style="clear:both;"></div>

{% if request.user.username == user.username %}
  {% include "includes/page_heading.html" with text="Your Recent Posts" %}
{% else %}
  {% include "includes/page_heading.html" with text="Recent Posts" %}
{% endif %}

{% if subjects %}
  {% include "includes/partial_subject.html" with subjects=subjects %}
{% else %}
<div class="card p-4 my-4 mx-0">
  <h6 class="text-center">No Posts Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any posts right now.</p>
  </div>
</div>
{% endif %}


<script type="text/javascript">
// Send Request
$(document).ready(function(){
  $("a#send_message_request").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $add_btn = $(this);
    var $add_url = $(this).attr("href");
    $.ajax({
      url: $add_url,
      type: 'GET',
      success: function (data) {
        $add_btn.text(data);

        if ($add_btn.hasClass('btn-outline-primary')) {
          $add_btn.removeClass('btn-outline-primary').addClass('btn-primary');
        }
        else if ($add_btn.hasClass('btn-primary')) {
          $add_btn.removeClass('btn-primary').addClass('btn-outline-primary');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

<script>
// Follow user
$(document).ready(function(){
    $("a#follow_user").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $follow_btn = $(this);
    var $follow_url = $(this).attr("href");
    $.ajax({
      url: $follow_url,
      type: 'GET',
      success: function (data) {
        $follow_btn.text(data);

        if ($follow_btn.hasClass('btn-outline-primary')) {
          $follow_btn.removeClass('btn-outline-primary').addClass('btn-primary');
        }
        else if ($follow_btn.hasClass('btn-primary')) {
          $follow_btn.removeClass('btn-primary').addClass('btn-outline-primary');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });
});
</script>
{% endblock %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %}<title>Account Settings | Elmer</title>{% endblock %}

{% block content %}
{% include "includes/page_heading.html" with text="Account Settings" %}

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'profile_edit' %}">Edit profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'picture_change' %}">Add picture</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
  </li>
</ul>

<form action="{% url 'profile_edit' %}" method="post">
  {% csrf_token %}
  {{ user_form|crispy }}
  <div class="form-group">
    <label for="id_dob">Date of Birth</label>
    {% render_field profile_form.dob class="form-control" %}
  </div>
  <button type="submit" class="btn btn-success btn-block">Save</button>
</form>
{% endblock %}

users/templates/users/view_all_contacts.html
{% extends "base.html" %}
{}


{% block title %}<title>Contact List | Elmer</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Contact List" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Contacts Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any contact right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/view_all_message_requests.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Message Requests | Elmer</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Message Requests" %}
{% for user in users %}
<div class="card" style="border:none; border-bottom:1px solid #dcd7d7; margin-bottom:5px;">
  <div class="card-body" style="padding:10px;">

    <div class="text-center" style="float:left; width:10%;">
      {% if user.profile.get_picture %}
      <img src="{{ user.profile.get_picture }}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h5 style="font-size:16px;">
        <a href="{% url 'user_profile' user.username %}"
           class="card-link"
           title="{{ user.username }}">{{ user.profile.screen_name }}</a>
        <a href="{% url 'accept_message_request' user.id %}"
           class="btn btn-outline-primary btn-sm"
           id="accept_message_request"
           style="float:right;"
           title="Confirm to start a conversation with this user">Confirm</a>
      </h5>
      <p>{{board.description|markdown|truncatewords_html:50}}</p>
      <p class="text-muted">Member since <span title="{{user.profile.member_since|date:"D d M Y"}} | {{user.profile.member_since|time:"H:i:s"}}">{{user.profile.member_since|naturaltime}}</span></p>
    </div>
  </div>
</div>
{% empty %}
<div class="card p-4 my-4 mx-0">
  <h6 class="text-center">No Requests Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any message requests received.</p>
  </div>
</div>
{% endfor %}

<script type="text/javascript">
// Confirm Request
$(document).ready(function(){
  $("a#accept_message_request").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $confirm_btn = $(this);
    var $confirm_url = $(this).attr("href");
    $.ajax({
      url: $confirm_url,
      type: 'GET',
      success: function (data) {
        $confirm_btn.text(data);

        if ($confirm_btn.hasClass('btn-outline-primary')) {
          $confirm_btn.removeClass('btn-outline-primary').addClass('btn-primary disabled');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

{% endblock content %}

users/templates/users/view_all_users.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Users | Elmer</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Users" %}
{% if users %}
  {% include "users/includes/partial_user.html" with users=users %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Users Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">There are no users right now.</p>
    </div>
  </div>
{% endif %}

{% endblock content %}